### ISSUE TITLE
Alternative Service Discovery Method

### ISSUE THREAD

**Issue by Auguss82** [ph202107/nordlist#1]
Sometimes the default method of connecting to NordVPN can be long. I found this a while back on reddit link to another project. Here is a simple curl script on the nordvpn recommendations website to connect to default recommended server. It may quicken or give an alternative method to connect to nordvpn instead of using the built in service.

bestserver="$(curl --silent 'https://nordvpn.com/wp-admin/admin-ajax.php?action=servers_recommendations' | jq --raw-output '.[0].hostname' | awk -F. '{print $1}')"
nordvpn c "${bestserver}"

**Comment by ph202107** [comment]
Hi!  This is a good idea, I have implemented it as "QuickConnect" on the main menu, and function fquickconnect.  Main menu items can be rearranged if you prefer it as #1.  One issue is that when connected to another country it will provide a recommended server in that country, so I have it disconnect first to recommend the best possible server.  Thanks!
