### ISSUE TITLE
Split tunneling  Feature not available 

### ISSUE THREAD

**Issue by ulrichando** [ph202107/nordlist#2]
First of all, I will say your app script is amazing. But my question s it possible to add Split tunneling  as well  on the settings ?

**Comment by ph202107** [comment]
Hi, thanks for the feedback!  This might work by using network namespaces (netns), but it also seems quite difficult to get working smoothly and without leaks.  Unfortunately I don't think I will be able to implement split-tunneling anytime soon.  If you are aware of an existing solution that works with Nord then please let me know!  Thanks
